### ISSUE TITLE
VBOs

### ISSUE THREAD

**Issue by demipixel** [mhsjlw/flying-squid#71] opened 2015-10-10 21:01 UTC
Turn on VBOs in video settings and watch the massacre begin.

- Chunks can sometimes disappear on the side of your view
- Sometimes flying too high will make all chunks disappear (only about 20 blocks above the surface)
- Sometimes chunks will not appear until you step into them
- Sometimes chunks will randomly disappear (sort of like the second) and will randomly appear or will appear when entered.

So since this doesn't happen in vanilla, clearly we're doing something wrong, however this all seems client side (turning off VBOs, none of this happens) so I'm curious as to what we could do to fix this.

**Comment by rom1504** [comment] 2015-10-10 21:34
I just tried and I can't reproduce it on a localhost server. On what server have you been trying this ?

**Comment by demipixel** [comment] 2015-10-10 21:46
Local host server. I'll record maybe in a bit.

**Comment by rom1504** [comment] 2015-10-10 21:49
It's probably a consequence of sending whole chunks (https://github.com/PrismarineJS/prismarine-chunk/issues/8)

**Comment by rom1504** [comment] 2015-10-12 17:14
@demipixel now that https://github.com/mhsjlw/flying-squid/issues/52 is fixed, this should be fixed, can you check ?

**Closed** 2015-10-12 21:54 UTC
