### ISSUE TITLE
Fix spawn animation

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#156] opened 2015-12-10 21:44 UTC
https://www.youtube.com/watch?v=PsQlDT_-Hoc&feature=youtu.be

it's just about letting the client handle despawning : remove https://github.com/mhsjlw/flying-squid/blob/master/src/lib/plugins/pvp.js#L73 (just check the client indeed despawn the mobs itself when they die)

video by @109C

**Comment by 109C** [comment] 2015-12-10 21:46
But if the client despawns them, then there will be invisible mobs.

**Comment by rom1504** [comment] 2015-12-10 21:49
no, the server know they are dead anyway.
We just don't need to force the client to despawn them by sending the despawn packet.

**Comment by 109C** [comment] 2015-12-10 21:49
But they shouldn't be dead? Doesn't it take more than one hit for sure for them to die?

**Comment by rom1504** [comment] 2015-12-10 21:51
ah, that's a separate problem.

Are you quite sure they are dead and not under the floor ? (I didn't notice that behavior on a non lagging server though, are you lagging ?)

**Comment by 109C** [comment] 2015-12-10 21:53
After I recorded the video, I check and they weren't hidden in the ground. Also, the server in the video thinks the mobs are still alive. (I used some packet spoofing magic to hit them, and sometimes they reappeared.)

**Comment by rom1504** [comment] 2015-12-10 21:55
okay, in what condition can you reproduce this ?

**Comment by 109C** [comment] 2015-12-10 22:08
1) spawn mobs
2) ```/kill @a```
3) Relogging sometimes helped cause the problem

I used to be able to reproduce this error consistently, but I restarted my client and it doesn't seem to happen when I do the above steps. I think this may be caused by some other unknown factor.

**Closed** 2015-12-11 00:14 UTC
Labels: bug, entities
